=== jaywritescode/Sudoku/src/test/resources/sudoku-abbreviated.schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "$id": "http://jaywritesco.de/schemas/sudoku-abbreviated.schema.json",
  "description": "A more abbreviated representation of a sudoku puzzle.",

  "type": "object",
  "properties": {
    "boxWidth": {
      "type": "number",
      "description": "The width of a box, in cells."
    },
    "boxHeight": {
      "type": "number",
      "description": "The height of a box, in cells."
    },
    "domain": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1,
        "maxLength": 1
      },
      "uniqueItems": true
    },
    "givens": {
      "type": "array",
      "items": [
        { "type": "number" },
        { "type": "number" },
        {
          "type": "string",
          "minLength": 1,
          "maxLength": 1
        }
      ],
      "minLength": 1,
      "uniqueItems": true
    }
  }
}

=== jaywritescode/Sudoku/src/test/resources/9x9-unsolved.json
{"boxHeight":3,"boxWidth":3,"domain":["1","2","3","4","5","6","7","8","9"],"givens":[{"row":1,"column":3,"digit":"4"},{"row":1,"column":7,"digit":"3"},{"row":2,"column":1,"digit":"1"},{"row":2,"column":2,"digit":"7"},{"row":2,"column":5,"digit":"5"},{"row":2,"column":8,"digit":"4"},{"row":3,"column":2,"digit":"6"},{"row":3,"column":4,"digit":"4"},{"row":4,"column":4,"digit":"8"},{"row":4,"column":9,"digit":"7"},{"row":5,"column":1,"digit":"3"},{"row":5,"column":6,"digit":"5"},{"row":5,"column":8,"digit":"9"},{"row":6,"column":2,"digit":"8"},{"row":6,"column":8,"digit":"5"},{"row":6,"column":9,"digit":"4"},{"row":7,"column":3,"digit":"5"},{"row":7,"column":4,"digit":"7"},{"row":7,"column":5,"digit":"6"},{"row":8,"column":1,"digit":"9"},{"row":8,"column":4,"digit":"1"},{"row":9,"column":5,"digit":"3"},{"row":9,"column":6,"digit":"4"},{"row":9,"column":8,"digit":"8"}]}
